apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: maxence-team-apptest
  namespace: observability
  labels:
    project: apptest
    team: maxence-team
spec:
  title: "maxence-team / apptest"
  instanceSelector:
    matchLabels:
      dashboards: grafana
